# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deployment_production:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    concurrency: deployment_production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run generate
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ci
        key: ${{ secrets.SSH_KEY }}
        source: dist
        target: /tmp/github-ci-deploy-prod-${{ github.sha }}
    - name: Post-Deployment Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ci
        key: ${{ secrets.SSH_KEY }}
        script: |
          rm -rf /www/wwwroot/lxfe-prod/* && \
          mv /tmp/github-ci-deploy-prod-${{ github.sha }}/dist/* /www/wwwroot/lxfe-prod && \
          chgrp -R www /www/wwwroot/lxfe-prod/* && \
          rm -rf /tmp/github-ci-deploy-prod-${{ github.sha }}
